name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r TimberHUN.zip huHU

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "TimberHUN.zip"
        skipIfReleaseExists: true

    - name: Extract mod.io metadata
      id: metadata
      run: |
        GAME_ID=$(jq '.modIo.game' huHU/manifest.json)
        echo "GAME_ID: $GAME_ID"
        echo GAME_ID=$GAME_ID >> $GITHUB_ENV
        MOD_ID=$(jq '.modIo.mod' huHU/manifest.json)
        echo "MOD_ID: $MOD_ID"
        echo MOD_ID=$MOD_ID >> $GITHUB_ENV
        MOD_VERSION=$(jq '.Version' huHU/manifest.json)
        echo "MOD_VERSION: $MOD_VERSION"
        echo MOD_VERSION=$MOD_VERSION >> $GITHUB_ENV
        GITHUB_REF_NAME="${GITHUB_REF##*/}"
        echo "CHANGELOG: $(git tag -l --format='%(contents)' $GITHUB_REF_NAME)"
        echo "CHANGELOG: $CHANGELOG"
        echo $CHANGELOG >> $GITHUB_ENV

    - uses: nickelc/upload-to-modio@v2.1.0
      with:
        token: ${{ secrets.MODIO_TOKEN }}
        game: ${{ env.GAME_ID }}
        mod: ${{ env.MOD_ID }}
        version: ${{ env.MOD_VERSION }}
        changelog: ${{ env.CHANGELOG }}
        path: TimberHUN.zip