name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r TimberHUN.zip huHU

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "TimberHUN.zip"

    - name: Extract mod.io metadata
      id: metadata
      run: |
        GAME_ID=$(jq '.modIo.game' huHU/manifest.json)
        MOD_ID=$(jq '.modIo.mod' huHU/manifest.json)
        VERSION=$(jq '.version' huHU/manifest.json)
        CHANGELOG=$(git for-each-ref $GITHUB_REF --format='%(contents)')

    - uses: nickelc/upload-to-modio@v2.1.0
      with:
        token: ${{ secrets.MODIO_TOKEN }}
        game: ${{ steps.metadata.outputs.GAME }}
        mod: ${{ steps.metadata.outputs.MOD }}
        version: ${{ steps.metadata.outputs.VERSION }}
        changelog: ${{ steps.metadata.outputs.CHANGELOG }}
        path: TimberHUN.zip