name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r TimberHUN.zip huHU
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "TimberHUN.zip"
